#!perl

use strict;
#use warnings;

use ScriptX
    'Run' => { code => sub { print "Hello, world!\n" } },
    ;

ScriptX->run;

# PODNAME:
# ABSTRACT: Say hello

=head1 DESCRIPTION

In this script we include one L<ScriptX> plugin: L<Run|ScriptX::Run>. This
plugin registers handler at the C<run> event. It can run one of several things:
C<code> (a coderef), C<command> (a shell command using L<IPC::System::Options>'s
C<system>).

[This documentation can be inserted by dzil plugin that reads from
ScriptX::CLI::Log] To enable logging, you can add this plugin:
L<CLI::Log|ScriptX::CLI::Log>, which basically loads L<Log::ger::App>. You can
then set environment variable, e.g. C<TRACE=1>:

    % SCRIPTX_IMPORT=-CLI::Log TRACE=1 script-eg-hello
