#!perl

use strict;
#use warnings;

use ScriptX
    'Run',
    ;

ScriptX->run;

sub run {
    print "Hello, world!\n";
}

# PODNAME:
# ABSTRACT: Say hello

=head1 DESCRIPTION

The L<Run|ScriptX::Run> plugin can also search for code to run in the
C<main::run()>.
